### PR TITLE
Updating the dependecies

### PR DESCRIPTION
**Pull request by Oussamaosman02**
I have updated the next dependencies:
- @testing-library/jest-dom : ^5.16.4 -> ^5.16.5
- @testing-library/react": ^13.3.0 -> ^13.4.0
- @testing-library/user-event: ^13.5.0 -> ^14.4.3 (major)
- react: ^18.1.0 -> ^18.2.0
- react-dom: ^18.1.0 -> ^18.2.0
- web-vitals: ^2.1.4 -> ^3.0.3 (major)

### CODE REVIEW

**Comment by obote998** [comment]
Love spells, Marriage spells - Bring lost lover back
Stop lover from cheating, be in control of the love in the house. Fix your troubled marriage. Tried many try me last, 35 years of experience. Stop or make a Divorce. Fix a Broken Marriage. Fall in Love & Commitment. Stop cheating.
Love spells, Marriage spells - Bring lost lover back Stop lover from cheating, be in control of the love in the house. Fix your troubled marriage. Tried many try me last, 35 years of experience. Stop or make a Divorce. Stop cheating. Fall in Love & Commitment. Fix a Broken Marriage.
Contact Me
www.chiefaberash.com
Get in Touch Get instant help for your love life now, with instant and guaranteed results.
Contact +27 63 5340727 Email info@chiefaberash.com

**Comment by codingmelo** [comment]
not bad

**Review by Supermajestcd — APPROVED** [review]

**Review by Supermajestcd — APPROVED** [review]

**Review by Supermajestcd — APPROVED** [review]

**Comment by joshaber** [comment]
This currently has conflicts but I'll be happy to take a look once those are resolved ⚡

**Comment by Oussamaosman02** [comment]
@joshaber I will open a new PR without conflicts because i deleted the fork and can't edit the files

**Comment by ezekingsley121** [comment]
Hi

**Pull request closed without merging**
